# Generated by Django 3.2.18 on 2023-03-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
