# Generated by Django 3.2.18 on 2023-03-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_book_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
